parameters:
#    karis_timesheet.example.class: Karis\TimesheetBundle\Example

services:
#    karis_timesheet.example:
#        class: %karis_timesheet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
