language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  
script: 
  - phpunit --coverage-text
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - hamdi.zayati@agencekarismatik.com
